import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser'; 
import chalk from 'chalk';
import rutasLogin from './routes/auth.routes';
import rutas from './routes/tareas.routes';
import "dotenv/config";
const app = express();
const PORT = process.env.PORT || 3000;
app.use(express.json());
app.use(cookieParser());
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173', credentials: true }));
app.use('/api/auth', rutasLogin);
app.use('/', rutas);
app.listen(PORT, () => console.log(chalk.grey(`Servidor corriendo en http://localhost:${PORT}`)));